name: Generate Conversation Video

on:
  schedule:
    - cron: '0 22 * * *'  # Runs every day at 5PM CST
  workflow_dispatch:      # Manual trigger

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install moviepy gTTS
          pip install --no-cache-dir moviepy gTTS
          pip install --no-cache-dir imageio-ffmpeg
          pip install --upgrade decorator proglog
          
      - name: List installed packages
        run: pip list
        
      - name: Create output directory
        run: mkdir -p video_output

      - name: Generate conversation video
        run: python create_video_conversation.py

      - name: Upload generated video as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated_convo_video
          path: video_output/generated_convo.mp4
