name: YouTube Auto Upload

on:
  schedule:
    - cron: '0 22 * * *'  # Runs daily at 5PM CST / 11PM UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  upload-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Create output directory
        run: mkdir -p video_output

      - name: Generate video
        run: python create_video.py

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python upload_video.py
