name: YouTube Auto Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # 5 PM CST

jobs:
  upload-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug Python and pip
        run: |
          which python
          python --version
          which pip
          pip --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir moviepy google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Verify moviepy import
        run: python -c "from moviepy.editor import TextClip; print('moviepy import successful')"

      - name: Create output directory
        run: mkdir -p video_output

      - name: Generate video
        run: python create_video.py

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python upload_video.py
