name: YouTube Auto Upload

on:
  schedule:
    - cron: '0 22 * * *'  # 5PM CST = 11PM UTC
  workflow_dispatch:

jobs:
  upload-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Create output folder
        run: mkdir -p video_output

      - name: Run Runway video generation
        env:
          RUNWAY_API_KEY: ${{ secrets.RUNWAY_API_KEY }}
        run: python runway_automation.py
