name: YouTube Auto Upload

on:
  schedule:
    - cron: '0 22 * * *'  # 5 PM CST
  workflow_dispatch:

jobs:
  upload-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker container and run
        run: |
          docker build -t yt-upload .
          docker run \
            -e YT_CLIENT_ID=${{ secrets.YT_CLIENT_ID }} \
            -e YT_CLIENT_SECRET=${{ secrets.YT_CLIENT_SECRET }} \
            -e YT_REFRESH_TOKEN=${{ secrets.YT_REFRESH_TOKEN }} \
            yt-upload
