name: Auto Video Creation & Upload

on:
  schedule:
    - cron: '0 22 * * *' # 5 PM CST = 11 PM UTC
  workflow_dispatch:

jobs:
  generate-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Generate video
        run: |
          mkdir -p video_output
          python create_video.py

      - name: Upload to YouTube
        run: |
          python upload_video.py
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
