name: AI Video Creator & Uploader

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install requests boto3 openai google-api-python-client

      - name: Generate scene via Runway
        env:
          RUNWAY_API_KEY: ${{ secrets.RUNWAY_API_KEY }}
        run: python runway_generate.py

      - name: Generate voiceover via Polly
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python tts_polly.py

      - name: Merge video + audio + subtitles
        run: python merge_and_subtitle.py

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python upload_video.py
