name: Daily News Combined Video

on:
  schedule:
    - cron: '0 14 * * *'  # 9 AM CST (UTC-5)
    - cron: '0 19 * * *'  # 2 PM CST (UTC-5)
    - cron: '0 23 * * *'  # 6 PM CST/CDT
  workflow_dispatch:
#  push:

jobs:
  Build-Combined-Video-Upload-Youtube:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🧰 Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            fonts-noto \
            fonts-noto-color-emoji \
            python3-dev \
            libxml2-dev \
            libxslt-dev \
            libjpeg-dev \
            zlib1g-dev \
            libsndfile1 \
            poppler-utils \
            libffi-dev \
            build-essential \
            libcairo2-dev \
            pkg-config

      - name: 📦 Install base Python dependencies
        run: |
          python -m pip install --upgrade pip

          # Install core packages individually to avoid dependency hell
          pip install requests
          pip install pydub
          pip install google-cloud-texttospeech
          pip install newspaper3k
          pip install lxml_html_clean
          pip install google-auth
          pip install google-auth-oauthlib
          pip install google-api-python-client
          pip install yt-dlp
          pip install google-generativeai

      - name: 📦 Install Cairo connector for Python
        run: pip install cairocffi

      - name: 📦 Install Cairosvg
        run: pip install cairosvg

      - name: List files with sizes to debug
        run: ls -Rlha

      - name: 🎬 Run video generation
        env:
          GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GNEWS_KEY: ${{ secrets.GNEWS_KEY }}
          GSEARCH_CSE_ID: ${{ secrets.GSEARCH_CSE_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python .github/workflows/create_combined_news.py

      - name: 📦 Upload Video Content as an Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: final-video-content
          path: final_content_combined.mp4
          retention-days: 7

      - name: List files with sizes to debug
        run: ls -Rlha

      - name: 🎬 Create final Video with intro
        run: |
          python .github/workflows/merge_intro_combined_content.py


      - name: 📦 Upload Video Final news as an Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: final-video-news
          path: final_news_combined.mp4
          retention-days: 7

      - name: List files with sizes to debug
        run: ls -Rlha

      - name: 🎬 Upload to YouTube
        env:
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
        run: |
          python .github/workflows/upload_video_combined.py