name: Video Generation and YouTube Upload

on:
  push:
    branches:
      - main # or your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation if using GCP service account

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # e.g., '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # --- CRITICAL FIX: Pin specific versions for known problematic dependencies ---
        # These versions are chosen to be recent and broadly compatible.
        # If one combination still fails, minor adjustments to these versions might be needed.
        pip install \
          "google-generativeai==0.3.0" \
          "google-cloud-aiplatform==1.40.0" \
          "google-auth-oauthlib==1.2.0" \
          "google-api-python-client==2.170.0" \
          "httplib2==0.22.0" \
          "pyparsing==3.1.2" \
          "requests==2.31.0" \
          # Add any other specific direct dependencies your script uses if not covered above

        echo "Dependencies installed. Running pip list for debugging:"
        pip list # This will show the exact versions installed if successful or on failure

    # Authenticate to Google Cloud using Workload Identity Federation
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        # --- CRITICAL FIX HERE ---
        # Replace with the EXACT resource name you copied from GCP.
        # It should be in the format: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
        workload_identity_provider: 'projects/381781776567/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider'
        service_account: 'vertex-ai-admin-or-vertex-ai-d@youtube-auto-uploader-463700.iam.gserviceaccount.com'
        # Ensure this service account has Vertex AI User and Service Usage Consumer roles,
        # and Workload Identity User role on the Workload Identity Pool.

    - name: Run Python script
      run: python .github/workflows/vertex_upload.py
      env:
        # GCP Project and Location for Vertex AI (Veo)
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_LOCATION: ${{ secrets.GCP_LOCATION }}
        # Veo Endpoint ID (only needed if using PredictionServiceClient, but let's keep it defined for now)
        VEO_ENDPOINT_ID: ${{ secrets.VEO_ENDPOINT_ID }}

        # Google API Key for Veo (if your python code uses google.generativeai for Veo)
        GOOGLE_API_KEY: ${{ secrets.GCP_API_KEY }}

        # YouTube API Credentials (from GitHub Secrets)
        YOUTUBE_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
