name: Video Generation and YouTube Upload

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Specify your Python version, e.g., '3.9', '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Upgrade google-cloud-aiplatform explicitly
        pip install --upgrade google-cloud-aiplatform google-auth-oauthlib google-api-python-client requests

    - name: Run Python script
      run: python .github/workflows/vertex_upload.py
      env:
        # Add any environment variables your script needs, e.g., for API keys
        VEO_API_KEY: ${{ secrets.GCP_SA_KEY }}
        # YouTube API Credentials (from GitHub Secrets)
        YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
        YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
        YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        # YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }} # If you pass client secrets as env vars
        # Make sure client_secrets.json and token.pickle are handled securely if not env vars
