name: Vertex_upload

on:
  schedule:
    - cron: '0 22 * * *'   # 5PM CST
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-cloud-aiplatform
    
      - name: Create output folder
        run: mkdir -p video_output

      - name: Generate video via Flow
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python .github/workflows/vertex_upload.py
